# Generated by Django 5.2.6 on 2025-10-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_rename_programstudi_mahasiswa_progamstudi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='progamstudi',
            new_name='programstudi',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='angkatan',
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
