# Generated by Django 5.2.6 on 2025-10-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0003_rename_progamstudi_mahasiswa_programstudi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.CharField(default=2023),
            preserve_default=False,
        ),
    ]
