# Generated by Django 5.2.6 on 2025-12-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0004_mahasiswa_angkatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.CharField(max_length=4),
        ),
    ]
